<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6f3d590f-02dd-4f98-ae2c-0b1c90ade239</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudStorage.Core\CloudStorage.Core.csproj" />
    <ProjectReference Include="..\CloudStorage.Infrastructure\CloudStorage.Infrastructure.csproj" />
    <ProjectReference Include="..\CloudStorage.Storage\CloudStorage.Storage.csproj" />
  </ItemGroup>

</Project>
